name: issue_event
on:
  issues:
    types: [opened, edited]
jobs:
  issue_event_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show the issue events
        run: |
          echo "An issue has been created and the info reg issue is listed below...."
          all_event = "${{ toJson(github.event) }}"
          event_title = "${{ github.event.issue.title }}"
          echo "All the metadata of events are - $all_event"
          echo "The issue title is - $event_title"
