name: issue_event
on:
  issues:
    types: [opened, edited]
jobs:
  issue_event_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show the issue events
        run: |
          echo "An issue has been created and the info reg issue is listed below...."
          echo "All the metadata of events are"
          echo "${{ toJson(github.event) }}"
          echo "The issue title is - ${{ github.event.issue.title }}"
